language: java

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install:
  mvn --settings .maven.xml install -DskipTests=true -B -V

notifications:
  email: false

cache:
  directories:
  - ~/.m2
